### ISSUE TITLE
#refactorer les models

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#12]
#refactorer les models :
tous les models doivent hériter de la même classe abstraite
cette classe doit contenir les méthodes save() / delete()
cette classe doit contenir un attribut de classe $manager qui fait référence au manager associé qui sera initialiser dans le __construct de chaque model.
la méthode loadByEmail($email) doit se trouver dans la classe Admin & User.
la méthode loadByEmail($email) doit faire appel au manager qui s'occupe d'hyrater le modèle.

**Comment by FlorianGG** [comment]
# Commit : 
* a9c1558775bbf7a080af1f801a48bbef43504763

## First step : 
* All the models are the children of the ModelAbstract class.
* The ModelAbstract class contains the methods delete and save
* This class has an attribute $manager which refer to the good manager
* This->manger is initialized in the __construct  of each model

## Next step : 
* Implementation  of the method loadByEmail($email) in Admin and User classes

**Comment by FlorianGG** [comment]
# Commit : 
* e0a4ce237de5925455853eb60bd3921b23a3c307

## Issue solve but  : 
* Method loadByEmail has been implemented in static in admin and user classes because I cannot create a new instance of Admin or User without add an array in parameter.
* This method must be create a new instance of his manager -> For me this solution is not good. This subject will be discussed during the next meeting
